### ISSUE TITLE
是否可以有LayoutManager版的代码

### ISSUE THREAD

**Issue by shuwenyouxi** [miaoyongjun/PageTransformer#1]

**Comment by mikaelzero** [comment]
这个库好久前写的了，你的需求其实已经有人做出来了，https://github.com/leochuan/ViewPagerLayoutManager

**Comment by LLLiuWeiJian** [comment]
尴尬，已经忘记是多久之前的需求了~~谢谢回复




------------------ 原始邮件 ------------------
发件人: "Zero"<notifications@github.com>;
发送时间: 2019年5月30日(星期四) 下午2:23
收件人: "moyokoo/PageTransformer"<PageTransformer@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [moyokoo/PageTransformer] 是否可以有LayoutManager版的代码 (#1)




这个库好久前写的了，你的需求其实已经有人做出来了，https://github.com/leochuan/ViewPagerLayoutManager
